<html lang="en" class="dark"><head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>ng么 ng么 Ц</title>
    <link href="https://fonts.bunny.net/css?family=instrument-sans:400,500,600" rel="stylesheet">
    <link rel="stylesheet" href="/static/css/app.css">
  <link rel="" as="script" crossorigin="" href="hehe"><style>
    #nprogress {
      pointer-events: none;
    }

    #nprogress .bar {
      background: #4B5563;

      position: fixed;
      z-index: 1031;
      top: 0;
      left: 0;

      width: 100%;
      height: 2px;
    }

    #nprogress .peg {
      display: block;
      position: absolute;
      right: 0px;
      width: 100px;
      height: 100%;
      box-shadow: 0 0 10px #4B5563, 0 0 5px #4B5563;
      opacity: 1.0;

      transform: rotate(3deg) translate(0px, -4px);
    }

    #nprogress .spinner {
      display: block;
      position: fixed;
      z-index: 1031;
      top: 15px;
      right: 15px;
    }

    #nprogress .spinner-icon {
      width: 18px;
      height: 18px;
      box-sizing: border-box;

      border: solid 2px transparent;
      border-top-color: #4B5563;
      border-left-color: #4B5563;
      border-radius: 50%;

      animation: nprogress-spinner 400ms linear infinite;
    }

    .nprogress-custom-parent {
      overflow: hidden;
      position: relative;
    }

    .nprogress-custom-parent #nprogress .spinner,
    .nprogress-custom-parent #nprogress .bar {
      position: absolute;
    }

    @keyframes nprogress-spinner {
      0%   { transform: rotate(0deg); }
      100% { transform: rotate(360deg); }
    }
  </style><title inertia=""> - Laravel</title><style type="text/css">.eruda-search-highlight-block{display:inline}.eruda-search-highlight-block .eruda-keyword{background:#332a00;color:#ffcb6b}</style><style type="text/css">@font-face{font-family:eruda-icon;src:url('data:application/x-font-woff;charset=utf-8;base64,d09GRgABAAAAAAvoAAsAAAAAEZgAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAABHU1VCAAABCAAAADsAAABUIIslek9TLzIAAAFEAAAAQAAAAFZHb1PUY21hcAAAAYQAAACVAAACUPKX+h1nbHlmAAACHAAAB1oAAAoQydSW4mhlYWQAAAl4AAAAMQAAADYYn0vGaGhlYQAACawAAAAdAAAAJAgEBBVobXR4AAAJzAAAABcAAABIRAb//GxvY2EAAAnkAAAAJgAAACYRiA/MbWF4cAAACgwAAAAfAAAAIAEjAQ1uYW1lAAAKLAAAASkAAAIWm5e+CnBvc3QAAAtYAAAAjwAAAMnZZQoFeJxjYGRgYOBiMGCwY2BycfMJYeDLSSzJY5BiYGGAAJA8MpsxJzM9kYEDxgPKsYBpDiBmg4gCACY7BUgAeJxjYGQ+zjiBgZWBgamX6QwDA0M/hGZ8zWDEyAEUZWBlZsAKAtJcUxgcPjJ+FGQBcWNYmBgYgTQIMwAA9pkJ13ic7ZHJDcMwDATHtnyf6iNVpKC8Um6aUAUOV5syQmA4EEEJAgn0QBc8ggTNmwbFK6pNrXcstZ541p6kesn3HblRjnOquY3eFC8OjEzMcW9lY+fg5CJHy8A/tpo/v1PWFE2da2uQO6P9lGQ06dIb7a4MBnk0yJNBng3yYrTTshrkzeh3ZTfIh0E+DfJlkLMhfwF2lyt5AAAAeJx1FltsFNf1nntnZ/YxO7PjnZ3ZB55ld9kZ73q9750FO9hYGDDYYLB5NLwMNRgCqFFpkhqFDz6IlKCUqLSfSb7cfkDVRCoVbdWgiqqNqoJUKYR+VMpHP9JWfXzSNu2ue+7sBreV4rXOPfee93OXAME/RtnPiUJIPusEwK0buhQAQxfpR3q4Ows/VOyU0n0TvqakxhW4i/eUE+6+2f1G2EkRT54+ZavER0gA2gFw6PnuO7vgdvfwLujAqZ3do91jO3t8LE+/xe2ALoGYdcBuuo1M3WD50BoJWRwYKiWqQb+i8ksI8DUW69u4yvLrsnZLa7p1Ewz6KnIGLcOwgsiNwutaOEaYZ/cT9gkJkhixvRhtx2412yBGUZXbqJuGaUBWAd2Cetttu03OQMNH9kwPD9fg3uzva93pvScOz0wXS91fvPrk6tUn/7h0fuvExNbzl56UitMzh4/NdadrMHFsH9yrDQ9P74HLVz/++5OrnOEzzum57/nxPnufmKSKUWi6mK2AxIHdnACnnwrQVTAx9blMP8Q0tDkwKDEGQwsfiKo46fPdnw8ZCmCI8F4PX0N8nQ6/WyOKEZq/7/NN4sMHC6FBw4CvSn1MhXVqvy4fsp9hrghg+bH0JtYR2C9Xuj/o3l2BWQ/A3pXuXbYLAcz+D4HHtrZGiAACIUWyHbWIKohOGWOagAqUwTXQfx4H5lmlpiEpGDeGXYG8bloYbr09DjztXCTrUeFpJDMWHwwPUEF/OTuv0Y0F7QUqsCvGFlGIXQh93QwKhpLQL1KBdrpDzs3ji79ZPH7TGfovFN5DHX2+VzLzWjFNtQvU51sxo1ZSv+hfMQcVrv8iFYUd5/9f2kOf1e0eu0fiXt2+qD5fWNB/ilihmOpVyAr2KiTC/XW8R/eq+R0/log3M7/GsEQi5/10bf2i9hn6ff0xO0wGSJrU0DMvc8/SyXPJsmVojkPdAl0BllVoDFu8YYzTZpnCv144deJmPn/zxKmPPkcujC6Nji69zMFYorpJz43lknjom6rsUKFw6+TiraFicejW4slbhULn0z4nAngeWRKbxrKAZwMl0LVeX02ya0Tle8HOZcWYphuNehvcJit2HodCmmlqQZmWDFqGWdHUOvs1U4KZgc3kmfwddgd7imAT5bKSKIk6n9WGF2BOoTlvlJt8Zr0pljIaG3nu7UMvnTm1ZXR0y6kzL53+0sEV80Xj2JXtR2ZwmnE4Z45Mjm0pfQ9eYSNbJ8c2n17649LpzWPFwq1jE6dbpeLuPd/fs7tYSsZHkGXdjwfsARnC3aFAtkxbDc+N9V3h+WZmNJPnmuoiG9+2enf12tSlysi+uZ/M7RupcOTEjm1bqze6P7rcI0492DY1dW316InP6R5jKlm5AdOXPdLd1Wf99xf2V5LwMpFzxqGF9cNq6hZt1N22GcNpRbea45RbVyj9bUktjrTPvvbW9eV2++z16ckrNRViC513a8d32vbO40u9A26otSuT09fPttvL19967Wx7pKiWun9egNg6Dz/6PvwUd2iUJDELuSy2PjY3z8Ig5FoZrQGSKTkSg0O3z52jy+Vk1M+mOocf0nOPHu14+Mbrd5bp8rlk1FLDtx91DoH2xsMdjx7RHKqVCFlbE3wCkG+SO+QxeUo+Ix2edHAnoIXZLeNM2TzLbdc7RN4H2T5BBQVw+HCn4KNHw0ANs/+J4bB6T/wVH6zeDuLcCNLQcL3WMeu9G17GcWF5ptoufzLwRC/65qF/9qhm36okDkPb9vzhsmXqYCY8Y54GjlHT8UQc9INjbc8p29t6DteAXNwQKjfbDko7ksk+VCxtIB6SjIHBcmJjQI7QgNTaLicFNR7bbyRVlpKs0bQSFJgEzJepqCUjFQgaEUGQtKg/LEgCgN8nS8GYEknKkqlZI4mNfllhsrRhdFMiaOrpaEEXFZ8/IscLzZQWEEGkqKka1EMm06KSnIiUIlHGJKG77cz8XGmEsXr9wMLi0vz+kTKl1erc/KL8B18wvKGye0oZ8Adi+Wy9MgmSX27HtXixEtfwzc42DL8ckX+lDwmBsOwXVDWghQWRGcwnFepmVNDLTqKSZ75dsXdLB2enz9I03RfUgnHHTWlBSZYTWSOd95k0FRdC/o2yHApnpCALJMJiVA0aoQF/bWMo4leMZHMoAtQXCInBoGEN5P2iX/D7RFmK2M+le5oycSsvGoKSjNhR1UchKIY3xKImz7JghKKBalpkVAJfILLBtePJSDRlumr3edaoHTy0fHL/3lKZ0XrtwMKXFw/Mlas/tvWEHJ3YpUbjg5bCRpubxaKWlLVQolBNDPA3usUSA35xDBPqjwyoGpN84ZAcEk1JDtvVuF7Uy5viNYeJq/rrhT/NzL0IaT5qax38PmUCxd87SYJTkscFKOLPHtzemfo4AH7vGDH+hWO3zKzNb7h0/tY9rruujjDgDrPqsBvo/NoqWvjfSOXzbj7/bVayUyn734+dSduepEdjlhXrfpfDp/mWbbfyaPo/itrIyAAAeJxjYGRgYABim4vFM+L5bb4ycLMwgMCt/cwpMPr/3///WVhZmIBcDgYQyQAARw4L3AAAAHicY2BkYGBhAAEW1v9///9lYWVgZEAFQgBbzAQjAAAAeJxjYGBgYMGL///HK88KVvMXAFerBEQAAAAAAAAgADQAUgBwALQBAAEiAZAB3AIsAkwCkALQAxIDQATKBQgAAHicY2BkYGAQYmRkYGcAASYg5gJCBob/YD4DAAsEATIAeJxlkD1uwkAUhMdgSAJSghQpKbNVCiKZn5IDQE9Bl8KYtTGyvdZ6QaLLCXKEHCGniHKCHChj82hgLT9/M2/e7soABviFh3p5uG1qvVq4oTpxm/Qg7JOfhTvo40W4S38o3MMbpsJ9POKdO3j+HZ0BSuEW7vEh3Kb/KeyTv4Q7eMK3cJf+j3APK/wJ9/HqDdPIFLEp3FIn+yy0Z3n+rrStUlOoSTA+WwtdaBs6vVHro6oOydS5WMXW5GrOrs4yo0prdjpywda5cjYaxeIHkcmRIoJBgbipDktoJNgjQwh71b3UK6YtKvq1VpggwPgqtWCqaJIhlcaGyTWOrBUOPG1K1zGt+FrO5KS5zGreJCMr/u+6t6MT0Q+wbaZKzDDiE1/kg+YO+T89EV6oAAAAeJxti9EOgjAUQ1fYBg4Vxe/go5ZxEZPJyOUmyN+7yKt9aE+aVhXqkFP/1aFACQ0Diwo1TnBocMYFV7S44Y4OD+U8c9r6SKM0B/LrOYkLnkn6IW1zc+CvNiGS5zqk98K0rnagSEKG8pEtfRY/DyXtpJfo94ppzKPJZCOxaz6GKUekIFpSinrzPCv1BZLnLysA') format('woff')}[class*=' eruda-icon-'],[class^='eruda-icon-']{font-family:eruda-icon!important;font-size:16px;font-style:normal;-webkit-font-smoothing:antialiased;-moz-osx-font-smoothing:grayscale}.eruda-icon-arrow-left:before{content:'\f101'}.eruda-icon-arrow-right:before{content:'\f102'}.eruda-icon-caret-down:before{content:'\f103'}.eruda-icon-caret-right:before{content:'\f104'}.eruda-icon-clear:before{content:'\f105'}.eruda-icon-compress:before{content:'\f106'}.eruda-icon-delete:before{content:'\f107'}.eruda-icon-error:before{content:'\f108'}.eruda-icon-expand:before{content:'\f109'}.eruda-icon-eye:before{content:'\f10a'}.eruda-icon-play:before{content:'\f10b'}.eruda-icon-refresh:before{content:'\f10c'}.eruda-icon-reset:before{content:'\f10d'}.eruda-icon-search:before{content:'\f10e'}.eruda-icon-select:before{content:'\f10f'}.eruda-icon-tool:before{content:'\f110'}.eruda-icon-warn:before{content:'\f111'}</style></head>
  <body class="font-sans antialiased">
    <div id="app" data-page="{
        &quot;component&quot;: &quot;views/home&quot;,
        &quot;props&quot;: {
          &quot;errors&quot;: {},
          &quot;name&quot;: &quot; ng么 ng么 Ц&quot;,
          &quot;quote&quot;: {
            &quot;message&quot;: &quot;&quot;,
            &quot;author&quot;: &quot;&quot;
          },
          &quot;auth&quot;: {
            &quot;user&quot;: null
          },
          &quot;ziggy&quot;: {
            &quot;port&quot;: null,
            &quot;defaults&quot;: [],
            &quot;routes&quot;: {
              &quot;home&quot;: {
                &quot;uri&quot;: &quot;/&quot;,
                &quot;methods&quot;: [&quot;GET&quot;, &quot;HEAD&quot;]
              },
              &quot;show-create-form&quot;: {
                &quot;uri&quot;: &quot;create-message/{id?}&quot;,
                &quot;methods&quot;: [&quot;GET&quot;, &quot;HEAD&quot;],
                &quot;parameters&quot;: [&quot;id&quot;]
              },
              &quot;create-form&quot;: {
                &quot;uri&quot;: &quot;create-message&quot;,
                &quot;methods&quot;: [&quot;POST&quot;]
              },
              &quot;login&quot;: {
                &quot;uri&quot;: &quot;login&quot;,
                &quot;methods&quot;: [&quot;GET&quot;, &quot;HEAD&quot;]
              },
              &quot;logout&quot;: {
                &quot;uri&quot;: &quot;logout&quot;,
                &quot;methods&quot;: [&quot;POST&quot;]
              },
              &quot;storage.local&quot;: {
                &quot;uri&quot;: &quot;storage/{path}&quot;,
                &quot;methods&quot;: [&quot;GET&quot;, &quot;HEAD&quot;],
                &quot;wheres&quot;: {
                  &quot;path&quot;: &quot;.*&quot;
                },
                &quot;parameters&quot;: [&quot;path&quot;]
              }
            },
            &quot;location&quot;: &quot;&quot;
          },
          &quot;message&quot;: &quot;&quot;,
          &quot;client&quot;: {
            &quot;fontName&quot;: &quot;Mali&quot;,
            &quot;color&quot;: &quot;#ff0019&quot;,
            &quot;messages&quot;: [
              &quot;i Love You&quot;,
              &quot;C岷m n 茫 岷n B锚n Anh&quot;
            ],
            &quot;music&quot;: &quot;//files.catbox.moe/vuh421.mp3&quot;
          },
          &quot;clientId&quot;: &quot;/&quot;
        },
        &quot;url&quot;: &quot;/&quot;,
        &quot;version&quot;: &quot;&quot;,
        &quot;clearHistory&quot;: false,
        &quot;encryptHistory&quot;: false
      }
      "><audio loop="" controls=""><source src="//files.catbox.moe/vuh421.mp3" type="audio/mpeg"></audio><div style="position: absolute; width: 100%; height: 100vh; overflow: hidden; pointer-events: auto; top: 0px; left: 0px; background-color: black; touch-action: none; -webkit-user-select: none;" data-camera-controls-version="2.10.0"><div style="width: 100%; height: 100%;"><canvas style="display: block; width: 375px; height: 624px;" data-engine="three.js r174" width="750" height="1248"></canvas></div></div></div>
  <script type="module" src="/static/js/app.js"></script>
  <script type="module" src="/static/js/home.js"></script>
  

</body><div class="__chii-hide__" style="display: none; position: absolute; pointer-events: none;"><div style="position: absolute; box-sizing: border-box; z-index: 100000;"></div><div style="position: absolute; box-sizing: border-box; z-index: 100000;"></div><div style="position: absolute; box-sizing: border-box; z-index: 100000;"></div><div style="position: absolute; box-sizing: border-box; z-index: 100000;"></div><div style="position: absolute; box-sizing: border-box; z-index: 100000; height: 25px; line-height: 25px; background-color: rgb(255, 255, 255); color: rgb(34, 34, 34); font-size: 12px; padding: 0px 5px; white-space: nowrap; overflow-x: hidden; box-shadow: rgba(0, 0, 0, 0.05) 0px 2px 2px 0px, rgba(0, 0, 0, 0.08) 0px 1px 4px 0px, rgba(0, 0, 0, 0.2) 0px 3px 1px -2px;"></div></div><div style="color: initial; color-scheme: initial; font-family: initial; font-feature-settings: initial; font-kerning: initial; font-optical-sizing: initial; font-palette: initial; font-size: initial; font-stretch: initial; font-style: initial; font-synthesis: initial; font-variant-alternates: initial; font-variant-caps: initial; font-variant-east-asian: initial; font-variant-ligatures: initial; font-variant-numeric: initial; font-variant-position: initial; font-variation-settings: initial; font-weight: initial; text-orientation: initial; text-rendering: initial; writing-mode: initial; -webkit-font-smoothing: initial; -webkit-locale: initial; -webkit-text-orientation: initial; -webkit-text-size-adjust: initial; -webkit-text-zoom: initial; letter-spacing: initial; accent-color: initial; border-collapse: initial; caption-side: initial; caret-color: initial; clip-rule: initial; color-interpolation: initial; color-interpolation-filters: initial; cursor: initial; empty-cells: initial; fill: initial; fill-opacity: initial; fill-rule: initial; glyph-orientation-horizontal: initial; glyph-orientation-vertical: initial; hanging-punctuation: initial; image-orientation: initial; image-rendering: initial; kerning: initial; line-break: initial; line-height: initial; list-style: initial; marker-end: initial; marker-mid: initial; marker-start: initial; orphans: initial; pointer-events: initial; print-color-adjust: initial; quotes: initial; resize: initial; shape-rendering: initial; speak-as: initial; stroke: initial; stroke-color: initial; stroke-dasharray: initial; stroke-dashoffset: initial; stroke-linecap: initial; stroke-linejoin: initial; stroke-miterlimit: initial; stroke-opacity: initial; stroke-width: initial; tab-size: initial; text-align: initial; text-anchor: initial; text-combine-upright: initial; text-decoration-skip-ink: initial; text-decoration-thickness: initial; text-emphasis-color: initial; text-emphasis-position: initial; text-emphasis-style: initial; text-indent: initial; text-shadow: initial; text-transform: initial; text-underline-offset: initial; text-underline-position: initial; visibility: initial; white-space: initial; widows: initial; word-break: initial; word-spacing: initial; word-wrap: initial; -apple-color-filter: initial; -apple-trailing-word: initial; -internal-text-autosizing-status: initial; border-spacing: initial; -webkit-box-direction: initial; -webkit-cursor-visibility: initial; -webkit-hyphenate-character: initial; -webkit-hyphenate-limit-after: initial; -webkit-hyphenate-limit-before: initial; -webkit-hyphenate-limit-lines: initial; -webkit-hyphens: initial; -webkit-line-align: initial; -webkit-line-box-contain: initial; -webkit-line-grid: initial; -webkit-line-snap: initial; -webkit-nbsp-mode: initial; -webkit-overflow-scrolling: initial; -webkit-rtl-ordering: initial; -webkit-ruby-position: initial; -webkit-tap-highlight-color: initial; -webkit-text-combine: initial; -webkit-text-decorations-in-effect: initial; -webkit-text-fill-color: initial; -webkit-text-security: initial; -webkit-text-stroke-color: initial; -webkit-text-stroke-width: initial; -webkit-touch-callout: initial; -webkit-user-modify: initial; -webkit-user-select: initial;"></div></html>
